name: Build and Deploy Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-linux:
        name: Build for Linux
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: remove .gitkeep
              run: |
                  rm -rf beat/out/.gitkeep

            - name: Set up dependencies
              run: |
                  sudo apt update
                  sudo apt install -y build-essential libcairo2-dev libgtk2.0-dev libgtksourceview2.0-dev

            - name: Build the project
              run: |
                  cd beat
                  make platform=linux

            - name: Upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build-outputs
                  path: beat/out/

    create-appimage:
        name: Create AppImage
        runs-on: ubuntu-latest
        needs: build-linux

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Download build artifacts
              uses: actions/download-artifact@v2
              with:
                  name: build-outputs
                  path: beat/out/

            - name: Set up AppImage dependencies
              run: |
                  sudo apt update
                  sudo apt install -y appimagetool

            - name: Create AppImage
              run: |
                  cd beat/out
                  appimagetool ./ ./beat.AppImage

            - name: Upload AppImage
              uses: actions/upload-artifact@v2
              with:
                  name: appimage
                  path: beat/out/beat.AppImage
